### PR TITLE
Update action to use NodeJS 16

### PR DESCRIPTION
**Pull request by RobPasMue**
Solves #19

### CODE REVIEW

**Comment by RobPasMue** [comment]
@vimtor I decided to create the PR myself, since the fix seemed pretty easy. Please feel free to adapt it as you may need! =)

**Review by germa89 — APPROVED** [review]
LGTM

**Comment by vimtor** [comment]
Thank you!

**Comment by RobPasMue** [comment]
My pleasure @vimtor! You may need to do a new release though to get the changes on the marketplace version of the action :)

**Pull request merged**
